
;   OFFSET HOOLDS THE STARTING ADDRESS OF A VARIABLE AS 16 BITS

; LEA COMPUTES AN ADDRESS BY THE SAME MEANS AND THEN STORE THE
; ADDRESS ITSELF IN THE TARGET RESISTER. IT IS USED AS A POINTER
; IN WHICH FIRST VARIABLE POINTS THE ADDRESS OF SECOND VARIABLE


; PRINTING IN DIFFERENT METHODS

; 16 BIT REGISTER DILE 16BIT ER ADDRESS DITE HOBE
; JEMON DW DIA SPACE/VARIABLE DEFINE KORE DL DIA PRINT KORA JABE NA  

ORG 100H
.MODEL SMALL

.DATA
VAR1 DB "HI GOODMORNING BARBIE$"  ; EIKHANE DB/DW JEKONO DILEI CHOLBE
VAR2 DB 10, 13, "HOW ARE YOU BARBIE?$"
VAR3 DW 5       ; PRINTING LINE STEP TA EIKHANE DILE PRINTING KORE NA SOMOSSA HOI
VAR4 DB 6

.CODE
MAIN PROC
    
    MOV AX, @DATA
    MOV DS, AX

    MOV DX, OFFSET VAR1 ; DX DITE HOBE,,,TASARA KAJ KORBE NAA
    MOV AH, 9
    INT 21H
    
    LEA DX, VAR2 ; DX DITE HOBE,,,TASARA KAJ KORBE NAA
    MOV AH, 9
    INT 21H
    
    MOV DL, 10
    MOV AH, 2
    INT 21H
    MOV DL, 13
    INT 21H
    
    ; THIS IS THE BEST WAY TO PRINT NON_STRING VARIABLE
    
    MOV DX, VAR3   ; EIKHANE DX DILE VAR3 TE DW DITE HOBE
    ADD DX, 48
    MOV AH, 2
    INT 21H
    
    MOV DL, 10
    MOV AH, 2
    INT 21H
    MOV DL, 13
    INT 21H
    
    MOV DL, VAR4   ; EIKHANE DL DILE VAR3 TE DB DITE HOBE
    ADD DL, 48
    MOV AH, 2
    INT 21H 

RET                                                                                        